<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>C# Parser for Unreal Engine packages &amp; assets</Description>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Berrysoft.XXTea" />
    <PackageReference Include="Blake3" />
    <PackageReference Include="BouncyCastle.Cryptography" />
    <PackageReference Include="FixedMathSharp" />
    <PackageReference Include="Fmod5Sharp" />
    <PackageReference Include="GenericReader" />
    <PackageReference Include="Infrablack.UE4Config" />
    <PackageReference Include="LZMA-SDK" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="OffiUtils" />
    <PackageReference Include="OodleSharp" />
    <PackageReference Include="Oodle.NET" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="K4os.Compression.LZ4.Streams" />
    <PackageReference Include="SubstreamSharp" />
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="System.Numerics.Tensors" />
    <PackageReference Include="VGAudio" />
    <PackageReference Include="Zlib-ng.NET" />
    <PackageReference Include="ZstdSharp.Port" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\ACE7Key.bin" />
    <EmbeddedResource Include="Resources\ACE7Key.bin" />
    <None Remove="Resources\PUBGNameHashMap.json" />
    <EmbeddedResource Include="Resources\PUBGNameHashMap.json" />
    <None Remove="Resources\BL4SoundTagsMap.json" />
    <EmbeddedResource Include="Resources\BL4SoundTagsMap.json" />
    <None Remove="Resources\ProSpiDecryptor.dll" />
    <EmbeddedResource Include="Resources\ProSpiDecryptor.dll.gz" />
    <None Remove="Resources\ShaderHashedNames.json" />
    <EmbeddedResource Include="Resources\ShaderHashedNames.json" />
  </ItemGroup>

</Project>
